name: Pull Request Checks

on:
  pull_request:
    branches:
      - 'main'
jobs:
  commit-lint:
    runs-on: ubuntu-latest
    container:
      image: ssouik/ubuntu-git:latest
    steps:
      - name: Check stuff
        run: ls
      - name: Checkout code
        run: |
          # Manually check out code since commit linting works better this way
          git clone https://github.com/SSouik/aws-s3-bucket.git code
          cd code
          git fetch
          git checkout ${GITHUB_HEAD_REF}
      - name: Lint pull request commits
        run: |
          commit-lint --pull-request
      
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
      - name: Initialize Terraform modules
        run: terraform init
      - name: Validate the Terraform
        run: terraform validate

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8
      - name: Initialize Terraform modules
        run: terraform init
      - name: Check the Terraform format
        run: terraform fmt -recursive -check
