name: Create Release

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'bin/**'
      - '.gitignore'
      - '.github/**'
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ssouik/ubuntu-git:latest
    steps:
      - uses: actions/checkout@v2
      - name: Create release
        run: |
          github-release \
            --user SSouik
            --token ${{ secrets.GITHUB_TOKEN }}
            --file version.json
            --org SSouik
            --repo aws-s3-bucket
