# Uncomment after initial merge
name: Pull Request Version Check

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'
      - 'bin/**'
      - '.gitignore'
      - '.github/**'
jobs:
  version-check:
    runs-on: ubuntu-latest
    container:
      image: ssouik/ubuntu-git:latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Version
        run: |
          version-check \
            --file version.json \
            --org SSouik \
            --repo aws-s3-bucket
